name: AlchemicLibrary
main: me.alchemi.al.Library
version: ${project.version}
api-version: 1.15
author: Alchemi
description: A library for all my plugins
softdepend:
- PlaceholderAPI

permissions:
  al.notify:
    default: op
    description: Allows user to get notifications about plugin updates.
    
  al.checkupdate:
    default: false
    description: Forces an update check when users with this node join.